# Generated by Django 4.2.7 on 2025-07-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playgrounds', '0002_playground_advance_booking_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Bkash', 'Nagad', 'Dutch Bangla Bank'", max_length=100)),
                ('method_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking'), ('digital_wallet', 'Digital Wallet'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/logos/')),
                ('instructions', models.TextField(help_text='Instructions for users on how to pay')),
                ('is_active', models.BooleanField(default=True)),
                ('is_instant', models.BooleanField(default=False, help_text='Instant verification possible')),
                ('requires_receipt', models.BooleanField(default=True, help_text='Requires payment receipt upload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('mobile_banking_number', models.CharField(blank=True, max_length=20)),
                ('mobile_banking_type', models.CharField(blank=True, help_text='e.g., Bkash, Nagad', max_length=50)),
                ('bank_qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/bank/')),
                ('mobile_qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/mobile/')),
                ('auto_approve_payments', models.BooleanField(default=False, help_text='Auto-approve payments for trusted playgrounds')),
                ('payment_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours to complete payment after booking')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('custom_instructions', models.TextField(blank=True, help_text='Playground-specific instructions')),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
                ('playground_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.playgroundpaymentconfig')),
            ],
            options={
                'unique_together': {('playground_config', 'payment_method')},
            },
        ),
        migrations.AddField(
            model_name='playgroundpaymentconfig',
            name='available_methods',
            field=models.ManyToManyField(through='payments.PlaygroundPaymentMethod', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='playgroundpaymentconfig',
            name='playground',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='playgrounds.playground'),
        ),
    ]
