# Generated by Django 4.2.7 on 2025-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['country', 'name']},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='country',
            field=models.CharField(choices=[('BD', 'Bangladesh'), ('IN', 'India'), ('PK', 'Pakistan'), ('LK', 'Sri Lanka'), ('NP', 'Nepal'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('OTHER', 'Other')], default='BD', help_text='Country/Region where this payment method is available', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency_code',
            field=models.CharField(default='BDT', help_text='Currency code (e.g., BDT, USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default processing fee percentage', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('name', 'country')},
        ),
    ]
