"""
Django settings for playground_booking project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Google Maps and External Services Configuration
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
MAPBOX_ACCESS_TOKEN = config('MAPBOX_ACCESS_TOKEN', default='')

# Business Configuration
CURRENCY = config('CURRENCY', default='USD')
CURRENCY_SYMBOL = config('CURRENCY_SYMBOL', default='$')
TIMEZONE = config('TIMEZONE', default='UTC')
BUSINESS_NAME = config('BUSINESS_NAME', default='PlayGround Booking')

# Brand & Theme Configuration
BRAND_COLORS = {
    'primary': config('BRAND_PRIMARY_COLOR', default='#3B82F6'),
    'secondary': config('BRAND_SECONDARY_COLOR', default='#8B5CF6'),
    'success': config('BRAND_SUCCESS_COLOR', default='#10B981'),
    'warning': config('BRAND_WARNING_COLOR', default='#F59E0B'),
    'danger': config('BRAND_DANGER_COLOR', default='#EF4444'),
    'dark': config('BRAND_DARK_COLOR', default='#1F2937'),
    'light': config('BRAND_LIGHT_COLOR', default='#F9FAFB'),
}

BRAND_LOGO = config('BRAND_LOGO_URL', default='/static/images/logo.png')
BRAND_FAVICON = config('BRAND_FAVICON_URL', default='/static/images/favicon.ico')
COMPANY_ADDRESS = config('COMPANY_ADDRESS', default='123 Business Street, City, State 12345')
COMPANY_PHONE = config('COMPANY_PHONE', default='+1 (555) 123-4567')
COMPANY_EMAIL = config('COMPANY_EMAIL', default='contact@playground.com')

# Company Information for Templates
COMPANY_INFO = {
    'name': config('COMPANY_NAME', default='Playground Booking System'),
    'email': COMPANY_EMAIL,
}

# Dynamic UI Text Configuration
UI_TEXT = {
    'sections': {
        'playground_details': config('UI_PLAYGROUND_DETAILS_TITLE', default='Playground Details'),
        'booking_details': config('UI_BOOKING_DETAILS_TITLE', default='Booking Details'),
        'booking_information': config('UI_BOOKING_INFO_TITLE', default='Booking Information'),
        'customer_information': config('UI_CUSTOMER_INFO_TITLE', default='Customer Information'),
        'special_requests': config('UI_SPECIAL_REQUESTS_TITLE', default='Special Requests'),
        'payment_details': config('UI_PAYMENT_DETAILS_TITLE', default='Payment Details'),
        'booking_timeline': config('UI_BOOKING_TIMELINE_TITLE', default='Booking Timeline'),
        'actions_section': config('UI_ACTIONS_SECTION_TITLE', default='Actions'),
        'actions': config('UI_ACTIONS_TITLE', default='Actions'),
    },
    'buttons': {
        'reschedule': config('UI_RESCHEDULE_BUTTON', default='Reschedule Booking'),
        'cancel_booking': config('UI_CANCEL_BOOKING_BUTTON', default='Cancel Booking'),
        'complete_payment': config('UI_COMPLETE_PAYMENT_BUTTON', default='Complete Payment'),
        'return_dashboard': config('UI_RETURN_DASHBOARD_BUTTON', default='Return to Dashboard'),
        'back_to_dashboard': config('UI_BACK_TO_DASHBOARD_BUTTON', default='Back to Dashboard'),
        'print': config('UI_PRINT_BUTTON', default='Print Receipt'),
        'contact_support': config('UI_CONTACT_SUPPORT_BUTTON', default='Contact Support'),
        'view_bookings': config('UI_VIEW_BOOKINGS_BUTTON', default='View All Bookings'),
    },
    'status': {
        'active': config('UI_STATUS_ACTIVE', default='Active'),
        'complete': config('UI_STATUS_COMPLETE', default='Complete'),
        'completed': config('UI_STATUS_COMPLETED', default='Completed'),
        'cancelled': config('UI_STATUS_CANCELLED', default='Cancelled'),
        'pending': config('UI_STATUS_PENDING', default='Pending'),
        'confirmed': config('UI_STATUS_CONFIRMED', default='Confirmed'),
        'payment_complete': config('UI_PAYMENT_COMPLETE', default='Payment Complete'),
        'booking_confirmed': config('UI_BOOKING_CONFIRMED', default='Booking Confirmed'),
        'payment_received': config('UI_PAYMENT_RECEIVED', default='Payment Received'),
        'booking_cancelled': config('UI_BOOKING_CANCELLED', default='Booking Cancelled'),
    },
    'labels': {
        'playground_name': config('UI_PLAYGROUND_NAME_LABEL', default='Playground'),
        'location': config('UI_LOCATION_LABEL', default='Location'),
        'address': config('UI_ADDRESS_LABEL', default='Address'),
        'name': config('UI_NAME_LABEL', default='Name'),
        'type': config('UI_TYPE_LABEL', default='Type'),
        'sports': config('UI_SPORTS_LABEL', default='Sports'),
        'capacity': config('UI_CAPACITY_LABEL', default='Capacity'),
        'players': config('UI_PLAYERS_LABEL', default='players'),
        'size': config('UI_SIZE_LABEL', default='Size'),
        'description': config('UI_DESCRIPTION_LABEL', default='Description'),
        'hourly_rate': config('UI_HOURLY_RATE_LABEL', default='Hourly Rate'),
        'rate': config('UI_RATE_LABEL', default='Rate'),
        'hour': config('UI_HOUR_LABEL', default='hour'),
        'hours': config('UI_HOURS_LABEL', default='hour(s)'),
        'date': config('UI_DATE_LABEL', default='Date'),
        'time': config('UI_TIME_LABEL', default='Time'),
        'start_time': config('UI_START_TIME_LABEL', default='Start Time'),
        'end_time': config('UI_END_TIME_LABEL', default='End Time'),
        'duration': config('UI_DURATION_LABEL', default='Duration'),
        'booking_id': config('UI_BOOKING_ID_LABEL', default='Booking ID'),
        'created_at': config('UI_CREATED_AT_LABEL', default='Booked On'),
        'booked_on': config('UI_BOOKED_ON_LABEL', default='Booked On'),
        'customer_name': config('UI_CUSTOMER_NAME_LABEL', default='Customer Name'),
        'username': config('UI_USERNAME_LABEL', default='Username'),
        'email': config('UI_EMAIL_LABEL', default='Email'),
        'phone': config('UI_PHONE_LABEL', default='Phone'),
        'total_amount': config('UI_TOTAL_AMOUNT_LABEL', default='Total Amount'),
        'total': config('UI_TOTAL_LABEL', default='Total'),
        'rate_per_hour': config('UI_RATE_PER_HOUR_LABEL', default='Rate per Hour'),
        'total_hours': config('UI_TOTAL_HOURS_LABEL', default='Total Hours'),
        'discount': config('UI_DISCOUNT_LABEL', default='Discount'),
        'final_amount': config('UI_FINAL_AMOUNT_LABEL', default='Final Amount'),
        'payment_status': config('UI_PAYMENT_STATUS_LABEL', default='Payment Status'),
        'payment_complete': config('UI_PAYMENT_COMPLETE_LABEL', default='Payment Complete'),
        'payment_pending': config('UI_PAYMENT_PENDING_LABEL', default='Payment Pending'),
        'booking_status': config('UI_BOOKING_STATUS_LABEL', default='Booking Status'),
        'special_requests': config('UI_SPECIAL_REQUESTS_LABEL', default='Special Requests'),
        'at': config('UI_AT_LABEL', default='at'),
    },
    'icons': {
        'back_arrow': config('UI_BACK_ARROW_ICON', default='←'),
        'check': config('UI_CHECK_ICON', default='✓'),
        'cross': config('UI_CROSS_ICON', default='✗'),
        'clock': config('UI_CLOCK_ICON', default='⏳'),
        'payment': config('UI_PAYMENT_ICON', default='💳'),
        'location': config('UI_LOCATION_ICON', default='📍'),
        'calendar': config('UI_CALENDAR_ICON', default='📅'),
        'user': config('UI_USER_ICON', default='👤'),
        'print': config('UI_PRINT_ICON', default='🖨️'),
        'email': config('UI_EMAIL_ICON', default='📧'),
        'cancel': config('UI_CANCEL_ICON', default='✗'),
        'reschedule': config('UI_RESCHEDULE_ICON', default='🔄'),
        'warning': config('UI_WARNING_ICON', default='❌'),
    },
    'messages': {
        'booking_not_found': config('UI_BOOKING_NOT_FOUND', default='Booking Not Found'),
        'booking_not_found_desc': config('UI_BOOKING_NOT_FOUND_DESC', default="The booking you're looking for doesn't exist or has been removed."),
        'cancel_confirm': config('UI_CANCEL_CONFIRM', default='Are you sure you want to cancel this booking?'),
        'cancel_success': config('UI_CANCEL_SUCCESS', default='Booking cancelled successfully.'),
        'cancel_error': config('UI_CANCEL_ERROR', default='Failed to cancel booking. Please try again.'),
        'support_subject': config('UI_SUPPORT_SUBJECT', default='Booking Support Request'),
    }
}

# Advanced Booking Configuration
DEFAULT_SLOT_DURATION = config('DEFAULT_SLOT_DURATION', default=60, cast=int)
DEFAULT_BREAK_DURATION = config('DEFAULT_BREAK_DURATION', default=15, cast=int)
MAX_ADVANCE_BOOKING_DAYS = config('MAX_ADVANCE_BOOKING_DAYS', default=30, cast=int)
MIN_BOOKING_NOTICE_HOURS = config('MIN_BOOKING_NOTICE_HOURS', default=2, cast=int)

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Payment Gateway Configuration
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-playground-booking-secret-key-for-development'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    
    # Custom apps
    'accounts',
    'playgrounds',
    'bookings',
    'notifications',
    'earnings',
    'adminpanel',
    'payments',
    'messaging',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'playground_booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'playground_booking.wsgi.application'
ASGI_APPLICATION = 'playground_booking.asgi.application'

# Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Import local settings if present (for AUTHENTICATION_BACKENDS etc)
try:
    from .settings_local import *
except ImportError:
    pass

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Explicitly set authentication backends for custom user model
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# Session Configuration
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = True

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Email Configuration (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
