# Generated by Django 4.2.7 on 2025-08-02 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0002_playground_advance_booking_days_and_more'),
        ('accounts', '0005_partnerapplicationvideo_partnerapplicationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('playground_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('hybrid', 'Indoor/Outdoor')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField(blank=True, null=True)),
                ('sport_types', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_playground_applications', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgrounds.city')),
                ('created_playground', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='playgrounds.playground')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='playground_applications/images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.playgroundapplication')),
            ],
        ),
    ]
