# Generated by Django 4.2.7 on 2025-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_auto_approved_booking_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Upload payment receipt for verification', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='receipt_verified',
            field=models.BooleanField(default=False),
        ),
    ]
