# Generated by Django 4.2.7 on 2026-02-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_booking_refund_amount_booking_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Upload payment receipt for admin verification', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='receipt_verified',
            field=models.BooleanField(default=False, help_text='Admin verification of payment receipt'),
        ),
    ]
