# Generated by Django 4.2.7 on 2025-07-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_receipt_booking_receipt_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playgrounds', '0002_playground_advance_booking_days_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('direct', 'Direct Message'), ('support', 'Support Ticket'), ('system', 'System Message'), ('broadcast', 'Broadcast Message')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('archived', 'Archived')], default='sent', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=notifications.models.default_dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_refund', 'Payment Refunded'), ('playground_approved', 'Playground Approved'), ('playground_rejected', 'Playground Rejected'), ('partner_approved', 'Partner Application Approved'), ('partner_rejected', 'Partner Application Rejected'), ('review_received', 'New Review Received'), ('review_request', 'Review Request'), ('system_announcement', 'System Announcement'), ('maintenance_notice', 'Maintenance Notice'), ('promotion', 'Promotional Offer'), ('achievement_unlocked', 'Achievement Unlocked'), ('weather_alert', 'Weather Alert'), ('price_change', 'Price Update')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notifications.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='playground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playgrounds.playground'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_5f59a5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient'], name='notificatio_sender__a88066_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_id'], name='notificatio_thread__2afdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='notificatio_message_826926_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='notificatio_created_5a3e36_idx'),
        ),
    ]
