# Generated by Django 4.2.7 on 2025-07-28 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import playgrounds.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days in advance can users book'),
        ),
        migrations.AddField(
            model_name='playground',
            name='auto_approval',
            field=models.BooleanField(default=False, help_text='Automatically approve bookings'),
        ),
        migrations.AddField(
            model_name='playground',
            name='available_days',
            field=models.JSONField(blank=True, default=playgrounds.models.default_list, help_text='Available days of the week', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='bank_details',
            field=models.JSONField(blank=True, default=playgrounds.models.default_dict, help_text='Bank account details for payments', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation policy'),
        ),
        migrations.AddField(
            model_name='playground',
            name='custom_pricing',
            field=models.JSONField(blank=True, default=playgrounds.models.default_dict, help_text='Custom pricing for different time slots or days', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='enable_chat',
            field=models.BooleanField(default=True, help_text='Allow chat with users'),
        ),
        migrations.AddField(
            model_name='playground',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps location URL', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='instant_booking',
            field=models.BooleanField(default=True, help_text='Allow instant booking'),
        ),
        migrations.AddField(
            model_name='playground',
            name='live_availability',
            field=models.BooleanField(default=True, help_text='Show real-time availability'),
        ),
        migrations.AddField(
            model_name='playground',
            name='operating_hours',
            field=models.JSONField(blank=True, default=playgrounds.models.default_dict, help_text='Daily operating hours', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='payment_methods',
            field=models.JSONField(blank=True, default=playgrounds.models.default_dict, help_text='Available payment methods and details', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='QR code for digital payments', null=True, upload_to='playgrounds/qr_codes/'),
        ),
        migrations.AddField(
            model_name='playground',
            name='refund_policy',
            field=models.TextField(blank=True, help_text='Refund policy'),
        ),
        migrations.AddField(
            model_name='playground',
            name='slot_templates',
            field=models.JSONField(blank=True, default=playgrounds.models.default_list, help_text='Time slot templates', null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PlaygroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='playgrounds/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='playgrounds/video_thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playgrounds.playground')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chats/attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='playgrounds.playground')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playground_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peak_hours', models.JSONField(blank=True, default=playgrounds.models.default_dict, null=True)),
                ('popular_days', models.JSONField(blank=True, default=playgrounds.models.default_dict, null=True)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('playground', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='playgrounds.playground')),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_spots', models.PositiveIntegerField(default=1)),
                ('total_spots', models.PositiveIntegerField(default=1)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='playgrounds.playground')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='playgrounds.timeslot')),
            ],
            options={
                'ordering': ['date', 'time_slot__start_time'],
                'unique_together': {('playground', 'date', 'time_slot')},
            },
        ),
    ]
