# Generated by Django 4.2.7 on 2025-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0002_playground_advance_booking_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('pending', 'Pending Approval'), ('draft', 'Draft')], default='pending', max_length=15),
        ),
    ]
