# Generated by Django 4.2.7 on 2025-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0004_create_playground_type_and_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly booking rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly booking rate', max_digits=10, null=True),
        ),
    ]
