# Generated by Django 4.2.7 on 2025-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0006_durationpass_remove_playground_price_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='playground_amenities',
            field=models.ManyToManyField(blank=True, help_text='Dynamic amenities with pricing', related_name='playgrounds', to='playgrounds.amenity'),
        ),
    ]
