# Generated by Django 4.2.7 on 2025-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0007_add_playground_amenities_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='default_currency',
            field=models.CharField(default='BDT', help_text='Default currency for pricing', max_length=3),
        ),
    ]
