# Generated by Django 4.2.7 on 2025-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0008_playground_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='playground',
            name='currency',
            field=models.CharField(default='BDT', help_text='Currency code (e.g., BDT, USD, EUR)', max_length=3),
        ),
    ]
