# Generated by Django 4.2.7 on 2026-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0009_remove_playground_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Currency code (USD, EUR, GBP, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='playground',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular to show on homepage'),
        ),
    ]
