# Generated by Django 4.2.7 on 2026-02-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgrounds', '0010_country_currency_code_playground_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlayground',
            fields=[
            ],
            options={
                'verbose_name': 'Popular Playground (Homepage)',
                'verbose_name_plural': '⭐ Popular Playgrounds (Homepage)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playgrounds.playground',),
        ),
    ]
